config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  # validate :name, {presence: true}
  before_validation :set_nameless_name
  validates :name, presence: true, length: { maximum: 30 }
  validate :validate_name_not_including_comma

  private

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end

  def set_nameless_name
    self.name = '名前なし' if name.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    # logger.debug(@current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # a
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session_params[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を削除しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf
    ul.navbar-nav.ml-auto
      - if current_user
        li.nav-item
          =link_to 'タスク一覧', tasks_path, class: 'nav-link'
        / li.nav-item
        /   =link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
        li.nav-item
          =link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item
          =link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
          .alert.alert-success= flash.notice
    = yield

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true do |f|
 .form-group
  = f.label :name
  = f.text_field :name, class: 'form-control', id: 'task_name'
 .form-group
  = f.label :description
  = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
 = f.submit nil, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの編集
.nav.justify-content-end
    = link_to  "一覧", tasks_path, class: 'nav-link'

= render partial: "form", locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧
= link_to  "新規登録", new_task_path, class: 'btn btn-primary'

.mb-3 
table.table.table-hover
  thead.thead-defalut
    tr
      th
        = Task.human_attribute_name(:name)
      th
        = Task.human_attribute_name(:created_at)
      th
  tbody
    - @tasks.each do |task|
      tr
        td
          = link_to task.name, task
        td
          = task.created_at
        td
          = link_to "編集", edit_task_path(task), class:'btn btn-primary mr-3'
          = link_to "削除", task, method: :delete, data:{confirm: "タスク「#{task.name}」を削除します。よろしいですか？"},
            class:'btn btn-danger'

          

app/views/tasks/new.html.slim
h1 タスクの新規登録
.nav.justify-content-end
    = link_to  "一覧", tasks_path, class: 'nav-link'

= render partial: "form", locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
    = link_to  "一覧", tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
      tr
        th
            = Task.human_attribute_name(:id)
        td
            = @task.id
      tr 
        th
            = Task.human_attribute_name(:name)
        td
            = @task.name
      tr 
        th
            = Task.human_attribute_name(:description)
        td
            = simple_format(h(@task.description),{},sanitize:false,wrapper_tag: "div")
      tr 
        th
            = Task.human_attribute_name(:created_at)
        td
            = @task.created_at
      tr 
        th
            = Task.human_attribute_name(:updated_at)
        td
            = @task.updated_at
= link_to "編集", edit_task_path, class: 'btn btn-primary mr-3'
= link_to "削除", @task, method: :delete, data:{confirm: "タスク「#{@task.name}」を削除します。よろしいですか？"}, class:'btn btn-danger'

app/views/tasks/test.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table class=table table-hover>
        <thead class=thead-defalut>
            <tr>
                <th><%= Task.human_attribute_name(:name) %></th>
                <th><%= Task.human_attribute_name(:created_at) %></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @Tasks.each do |task| %>
            <tr>
                <td><%= link_to(task.name, task) %></td>
                <td><%= task.created_at %></td>
            </tr>                
            <% end %>
            
            <% if task.errors.present? %>
                <ul id="error_explanation">
                    <% task.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                </ul>
            <% end %>
            
        </tbody>
    </table> 
</body>
</html>